# **Introduction to Python for Machine Learning**

In [7]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## (a) Create an array of 10 random integers between 1 and 100, and then calculate the mean and standard deviation of the array.


In [14]:
matriz = np.random.randint(1, 101, size=10)

# Calcular la media del array
#media = np.mean(matriz)
media2 = matriz.mean()

# Calcular la desviación estándar del array
#desviacion_estandar = np.std(matriz)
desviacion_estandar2 = matriz.std()
#Imprimir el tipo de objeto
print(type(matriz))
# Imprimir el array, la media y la desviación estándar

print("Matriz:", matriz)
#print("Media:", media)
print("Media:", media2)
#print("Desviación estándar:", desviacion_estandar)
print("Desviación estándar:", desviacion_estandar2)

<class 'numpy.ndarray'>
Matriz: [100  53   3  92  65  41  40  30  81  32]
Media: 53.7
Desviación estándar: 29.044965140278617


## (b) Create a 2-dimensional array of 3 rows and 4 columns with random integer values. Then, calculate the sum of each row and column.

In [12]:
# Crear la matriz aleatoria
matriz = np.random.randint(1, 10, size=(3, 4))
print("Matriz:")
print(matriz)

# Calcular la suma de cada fila
suma_filas = np.sum(matriz, axis=1)
print("Suma de cada fila:", suma_filas)
#print()

# Calcular la suma de cada columna
suma_columnas = np.sum(matriz, axis=0)
print("Suma de cada columna:", suma_columnas)


Matriz:
[[5 6 7 9]
 [2 7 9 8]
 [4 7 5 8]]
Suma de cada fila: [27 26 24]
Suma de cada columna:
[11 20 21 25]
